depromeet/moodpic-web

- .github/ISSUE_TEMPLATE/QUESTION.md
이슈 탬플릿 오타 수정
Fixes (issue #13)
- Question 이슈 탬플릿 내부 오타 수정
> Question 이슈 탬플릿 내부 오타 수정

- pages/_app.tsx
_app.tsx 내 부적절한 부분에 괄호 하나가 있어서 삭제하였습니다.
> MyApp 반환되는 JSX 내 괄호 제거

- .storybook/main.js
- .storybook/preview.js
- components/Common/StoryExample/StoryExample.stories.tsx
- components/Common/StoryExample/StoryExample.tsx
- package-lock.json
- package.json
Storybook 셋팅 추가와 예제 코드 추가했습니다. 추가 원하시는 애드온 있으시면 말씀해주세요!
[devDependencies 추가 내역]
- storybook addon(actions, essentials, interactions, links)
- babel-loader
- eslint-plugin-storybook
- react-docgen-typescript-loader
Fixes (issue #14)
- package.json에 스토리북 관련 script 추가(storybook, build-storybook)
- package.json에 devDependencies 추가
> Storybook 셋팅 및 예제 코드 추가

- components/Example/Example.styles.ts
- components/Example/Example.tsx
- pages/_app.tsx
- theme.d.ts
- tsconfig.json
현재 절대경로를 사용할 때, tsconfig.json 에 @styles, @components 와 같이 별칭을 별도로 사용하고 있었습니다.
그 부분을 하나의 별칭으로만 사용할 수 있게 변경하고자 하였습니다.
- tsconfig.json paths 를 `@/*` 만 사용할 수 있게 변경
- import 하고 있는 코드를 맞춰서 절대경로로 변경
> tsconfig.json paths 변경

- pages/_app.tsx
- pages/_document.tsx
- styles/globals.css
- styles/theme.ts
#21 Color, Typography 추가
- Pretendard 추가했습니다.
- global line-height 1.2 로 변경하였습니다. (normal -> 1.2)
- html, body font-size: 62.5% 로 변경하였습니다. (rem 10배수로 작업할 수 있게 하고자)
- theme colors hex 값 변경, fonts 추가
> 디자인 시스템 - Color, Typography 추가

- .github/workflows/front-test.yml
- components/Common/StoryExample/StoryExample.test.tsx
- 테스트 자동화
- pr등록시 github action을 이용해 테스트 수행 
테스트 성공시 잘 넘어가는 걸 확인했고, 실패 시 잘 잡아주는 것을 확인했습니다. 추가로 변경 원하시는 부분 있으시면 코멘트 주세요!
Fixes (issue #12 )
- .github/worksflows 디렉토리 추가
- .github/worksflows/front-test.yml 파일 추가 
> Github Action을 이용한 테스트 자동화

- components/Card/Card.stories.tsx
- components/Card/Card.styles.ts
- components/Card/Card.tsx
#21 - Card component 추가
- Card 컴포넌트 추가 (stories 추가)
> 공용 컴포넌트 - Card component 추가

- components/Common/Toggle/Toggle.stories.tsx
- components/Common/WritingButton/WritingButton.stories.tsx
- components/Common/WritingButton/WritingButton.tsx
(#36)
- storybook에 Toggle 추가
- storybook에 WritingButton 추가
> Toggle, WritingButton 스토리북에 추가 (#36)

- components/Common/Button/Button.tsx
- components/Home/Banner.tsx
- components/Home/Tab.tsx
- components/Home/TabHeader.tsx
- components/Home/Tabs.tsx
- pages/index.tsx
- shared/constants/home.ts
(#25)
https://user-images.githubusercontent.com/29244798/164910774-ec4b2b9d-5e70-412d-9985-c8f479c3f861.mov
- Tab 관련 상수 추가
- Home/Banner 컴포넌트 추가
- Home/Tabs 컴포넌트 추가
🗒️ Common 컴포넌트처럼 styles 관련 코드를 분리하지 않고 single file component 형태로 작성해봤습니다. 제 의견 PR 에 올리고자 이대로 올려봤습니다.
- Button 컴포넌트 default parameter -> defaultProps 를 사용하였습니다.
🗒️ default parameter 로 하더라도 required property 로 인터페이스를 설계하면 컴포넌트 사용 시 props 로 꼭 전달을 해줘야 하더라구요..!
그래서 defaultProps 를 사용하였는데, 이 부분에 대해서 의견 주시면 좋을 것 같아요.
> 메인 페이지 - 배너, 탭 컴포넌트 추가

- components/Common/ChipButton/ChipButton.tsx
- components/Common/WritingButton/WritingButton.tsx
- package-lock.json
- package.json
- pages/_app.tsx
- store/toast/atom.ts
Fixes (issue #54)
- recoil dependency 추가하였습니다.
- atom 에 대한 가이드라인만 우선 추가하였습니다.
- react-query 를 쓰고 있어서 비동기 관련해서 쓸 일이 있을지 잘 모르겠어서 selector 관련해서는 우선 추가하지 않았어요!
**Example**
atom 의 state 를 read/write 할 때는 아래와 같이 useRecoilState 메서드 사용
atom 의 state 를 write 만 할 때는 아래와 같이 useSetRecoilState 메서드 사용
```jsx
// pages/index.tsx
import { useRecoilState } from 'recoil';
import { toastStateAtom }  from '@/store/toast/atom';
const Home = () => {
const [toast, setToast] = useRecoilState(toastStateAtom);
return (
<>
...
<button onClick={() => setToast(!toast)}>Open Toast</button>
</>
);
};
```
atom 의 state 를 read 만 할 때는 아래와 같이 useRecoilValue 메서드 사용
```jsx
// pages/index.tsx
import { useRecoilValue } from 'recoil';
import { toastStateAtom }  from '@/store/toast/atom';
const AppLayout = ({ children }: …
```
> recoil 추가 (#54)

- components/Common/Button/Button.stories.tsx
- components/Common/Button/Button.styles.ts
- components/Common/Button/Button.tsx
- styles/theme.ts
Fixes (issue #21)
- font-size h2 함수 추가
- button size small 추가
**medium**
**small**
> 디자인 시스템 h2, button size 추가 (#21)

- jest.config.js
jest.config에 theme 경로 설정(theme 모듈 찾지 못하는 문제 해결)
Fixes (issue #79 )
- jest.config 설정 변경
> jest.config에 theme 경로 설정(theme 모듈 찾지 못하는 문제 해결)

- components/Common/Button/Button.stories.tsx
- components/Common/Button/Button.styles.ts
Fixes (issue #36)
**type: primary, size: medium, disabled**
**type: primary, size: medium**
**type: primary, size: small, disabled**
**type: primary, size: small**
- button disabled UI 추가
- medium size 최소 padding 수정
> button style 수정 (#36)

- components/Common/Button/Button.styles.ts
Fixes (issue #36)
- button large 에 disabled style 추가
https://user-images.githubusercontent.com/29244798/166472480-f5f71ef3-f173-4d1b-bbde-8151142a7060.mov
> button large size 에 disabled style 추가

- components/Post/PostItem.tsx/PostItem.stories.tsx
- components/Post/PostItem.tsx/PostItem.tsx
- pages/index.tsx
- pages/posts/undefined-feelings.tsx
- shared/type/post.ts
feature #64
- /posts/undefined-feelings 페이지 추가
- PostItem 에 isMine props 추가
> 2차 감정 미선택 기록 페이지 추가 

- components/Common/BottomSheetContainer/BottomSheetContainer.tsx
- components/Common/DropdownMenu/DropdownMenu.tsx
- components/Home/Header/Header.tsx
- hooks/useAnimation.ts
feature #25
메인페이지 드롭다운 애니메이션 추가
- useAnimation hooks 추가
- bottomSheet animation, dropdown animation 같이 사용할 수 있게 hooks 로 분리
https://user-images.githubusercontent.com/29244798/167107324-7424c27f-b256-478e-89e6-dc5ea50b550e.mov
> useAnimation hooks 추가, Dropdown animation 추가

- components/Common/AppLayout/AppLayout.styles.ts
- components/Home/CollectedFolder/CollectedFolder.styles.ts
- components/Home/CollectedFolder/CollectedFolder.tsx
- components/Home/Folder/Folder.styles.ts
- components/Home/Folder/Folder.tsx
- components/Home/FolderList/FolderList.tsx
- hooks/query/useFoldersQuery.ts
- next.config.js
- pages/index.tsx
- shared/constants/queryKey.ts
- shared/type/folder.ts
Fixes (#92) 
#92 PR 을 feat/msw 로 머지하는 바람에 main 으로 머지하는 PR 을 한번 더 올리게 되었습니다. :pray:
> #92 PR 머지를 위한 PR

- components/Home/Header/Header.stories.tsx
- components/Home/Header/Header.styles.ts
- components/Home/Header/Header.tsx
- pages/index.tsx
Feature (issue #23)
- Floating action button, 우측 writing button 애니메이션을 위해 eventListener 추가
https://user-images.githubusercontent.com/29244798/167659653-f50244bb-3d45-487a-8a9d-032a0e1b5715.mov
> 메인페이지 Header, FAB animation, style 추가

- service/apis/authService.ts
- authService data destructuring 변경
> authService destructuring 수정

- components/Common/TextField/TextField.styles.ts
- components/Common/TextField/TextField.tsx
Textfield  rightSideIcon 크기 문제로 인한 변경
Fixes (issue #94)
- TextField Container 스타일 속성   flex-direction: column; 제거
- TextField Container 스타일 속성   align-items: center; 추가 
> TextField rightSideIcon 크기 문제로 인한 변경

- components/Common/Toast/Toast.styles.ts
- components/Common/Toast/Toast.tsx
- components/Post/PostItem/PostItem.tsx
- components/Post/PostList/PostList.tsx
- hooks/apis/post/index.ts
- hooks/apis/post/usePostMutation.ts
- hooks/useToast.ts
- pages/posts/[postId].tsx
- pages/posts/index.tsx
- shared/type/common.ts
- shared/type/global.d.ts
- store/toast/atom.ts
Feature (issue #102)
**기록 삭제 기능 추가**
https://user-images.githubusercontent.com/29244798/169311578-0fc5e5d7-40db-40d2-9fa2-035eeca55849.mov
- @/shared/type/global -> @/shared/type/common 으로 ToastType 변경
- ToastType import 경로 수정
- usPostMutation 함수 추가, postService 에 deletePostById 함수 추가
- 기록 상세 페이지에서 삭제 클릭 시, deleteMutation 함수 실행
> 기록 삭제 기능 추가 (#102)

- pages/posts/[postId].tsx
우선은 대충 작성했습니다!
Fixes (issue #144 )
- 공유 버튼 누르면 router.push
> feat: 공유 버튼 눌렀을 떄 share 페이지로 이동하는 기능 추가

- components/Post/PostList/PostList.tsx
- hooks/useBottomSheet.ts
- pages/posts/index.tsx
- shared/utils/fetcher.ts
Fixes (issue #62)
- baseURL 수정
- NODE_ENV 상관없이 https://api.moodpic.kr 로 변경
- PostList 컴포넌트 isMine false 로 변경
- PostList 컴포넌트 하단에 margin-bottom 2rem 추가
- bottomSheet hooks isVisibleSheet false 일 때 body.overflow unset 으로 변경해주는 작업 추가
> PostList 컴포넌트 isMine false 로 전달, 스타일 수정

- components/Common/AppLayout/AppLayout.styles.ts
- components/Common/AppLayout/AppLayout.tsx
- components/CurrentEmotion/CurrentEmotion.tsx
- components/Question/Question.styles.ts
- components/Question/Question.tsx
- pages/_document.tsx
> refactor: 태그 +버튼 클릭시 전역 상태에 추가되도록 수정

- components/TagSearch/PopularTagItem/PopularTagItem.tsx
- components/TagSearch/SearchField/SearchField.tsx
- hooks/useSearchForm.ts
- pages/search/index.tsx
- pages/search/result/[searchedTag].tsx
- shared/type/post.ts
검색 기능 이슈 해결 
Fixes (issue #156 )
- 빈 문자열 검색시 발생하는 이슈 수정
- 빈 문자열이 아닌 공백(스페이스 등)으로 검색하면 발생하는 문제 해결
위 두개에서는 서버에서도 에러가 나는 것 같습니다.
- 인기 태그 타이틀 외 주변 영역 클릭해도 검색되는 부분 -> 타이틀 클릭을 통해서만 검색 할 수 있도록 변경
- 인기 태그나 최근 검색 태그를 클릭해 검색 할 때 최근 검색 기록에 추가되지 않는 이슈 수정
- 태그 검색 후 최신 태그 중복으로 나오는 방법에서 -> 중복 제거하고 맨 앞에 위치 시키는 방식으로 변경 
- 최근 검색 결과 반대로 나오는 부분 해결 
> Fix 검색 기능 

- components/Common/ReadyForOpen/ReadyForOpen.tsx
- components/PreEmotion/PreEmotion.tsx
QA 가즈아~~~
- Change 1
- Change 2
> style: 간단한 qa

- components/Home/CollectedFolder/CollectedFolder.styles.ts
- components/Home/FloatingButtonGroup/FloatingButtonGroup.tsx
- components/Home/TabHeader/TabHeader.tsx
- components/Post/PostList/PostList.tsx
- pages/posts/[postId]/edit.tsx
- pages/posts/index.tsx
- service/apis/postService.ts
- shared/utils/date.ts
https://www.notion.so/depromeet/QA-27c48bd47fd94b6f94e17b464532caeb
QA 이슈 수정
- 모든 폴더 folder background 변경하였습니다.
- formatDatetime dayPeriod 노출 될 수 있게 변경하였습니다.
- writing button banner 이후 노출될 수 있게 변경하였습니다.
- getPostsByCategories data.reverse() 실행해서 data 역순으로 노출될 수 있게 변경하였습니다.
> 메인페이지 QA 이슈 해결

- components/Common/Button/Button.styles.ts
- components/Common/Button/Button.tsx
- components/Common/TextField/TextField.styles.ts
- components/Common/TextField/TextField.tsx
- components/Dialog/DialogFolderForm.tsx
- components/Share/CategoryOptionItem/CategoryOptionItem.tsx
- components/TagSearch/SearchField/SearchField.tsx
- hooks/useSearchForm.ts
- pages/search/index.tsx
- pages/search/result/[searchedTag].tsx
- pages/share/index.tsx
- pages/share/post/[ldm].tsx
- shared/utils/copyClipboard.ts
- styles/theme.ts
검색 관련 여러 이슈 처리했습니다.
Fixes (issue #156 )
> 검색 기능 수정 사항 반영

- components/Post/PostItem/PostItem.tsx
- pages/posts/[postId].tsx
- pages/posts/[postId]/edit.tsx
- pages/search/result/[searchedTag].tsx
- shared/utils/date.ts
https://www.notion.so/depromeet/QA-27c48bd47fd94b6f94e17b464532caeb
- formatDate 포맷팅 함수 추가하였습니다.
- `yyyy년 MM월 dd일`
- 조회수, 날짜 노출 조건을 변경하였습니다.
- 검색 페이지에서 태그, MY 노출될 수 있게 변경하였습니다.
> Fix: 리스트 페이지, 상세 페이지 내 날짜/조회수 포맷 변경

- hooks/useSearchForm.ts
- pages/search/index.tsx
- pages/search/result/index.tsx
검색 관련 이슈 및 추가 기능 구현
Fixes (issue #181 )
- 검색 후 검색 안 되는 문제 해결
- 검색에 자동으로 # 추가되는 기능 제거(추후에 기능 추가)
- 검색 결과 페이지에서 input 값에 결과 값 유지시켜주는 기능 추가 
- 검색 페이지 path-param -> query param 으로 변경했습니다. 
> 검색 관련 이슈 및 추가 기능 구현

- components/Common/ReadyForOpen/ReadyForOpen.tsx
> style: 텍스트 중앙 맞추기

- shared/constants/url.ts
> hotfix: baseurl 변경

- components/Common/WritingButton/WritingButton.tsx
- components/Home/Header/Header.tsx
- next.config.js
next/image config setting을 해보자
Fixes (issue #197)
- Change 1
- Change 2
> refactor: next/image config setting 및 프리로드

- components/Common/TextField/TextField.styles.ts
- components/Common/TextField/TextField.tsx
- components/TagSearch/SearchField/SearchField.tsx
- pages/search/result/index.tsx
- public/svgs/magnifyingglass-opacity.svg
> 검색 기능 관련 이슈 

- pages/_app.tsx
- pages/_document.tsx
기본 Meta tag title, description 을 수정합니다.
- meta tag title, description 텍스트 변경하였습니다.
> Feature: meta tag title, description 변경

- pages/_document.tsx
- pages/_middleware.ts
- pages/login/index.tsx
- pages/oauth/index.tsx
- shared/constants/routes.ts
> hotfix: 로그인페이지 이미지 렌더링 차단 , 카카오 로그인 리다이렉트 차단 수정

- components/Common/WritingButton/WritingButton.styles.ts
- components/Home/FloatingButtonGroup/FloatingButtonGroup.tsx
- components/Post/PostList/PostList.style.ts
- pages/404.tsx
- pages/posts/index.tsx
Fixes (issue https://github.com/depromeet/11th_5team_fe/issues/205)
- 404 페이지 fixed button wrapper 추가하여 480px 내에 추가될 수 있게 변경하였습니다.
- CommonWritingButton 위치 조정하였습니다.
> Fix: 404 페이지 버튼 스타일 수정, WritingButton 위치 조정

- components/Common/LohoHeader/LohoHeader.tsx
- pages/share/index.tsx
- pages/share/post/[ldm].tsx
Fixes (issue #212 )
- float 버튼으로 변경
- 로고 마진 조절
- 텍스트 필드 누르는 것 수정
- 버튼 사이즈 변경
> 공유하기 추가 요구 사항 구현

- pages/share/post/[ldm].tsx
> [WIP] 공유하기 확인 방식 수정

- hooks/useAddToHomescreenPrompt.ts
- pages/login/index.tsx
- public/manifest.json
> feat: android 에서 add home screen 관련 툴팁 노출되게끔 추가

- pages/share/index.tsx
- pages/share/post/[ldm].tsx
공유하기 요구사항 반영
- 공유하기 버튼 컬러 변경
- 질문지로 입력한 경우 구분해서 보여주는 기능 
- 글자 수 길이 제한
> 공유하기 요구사항 반영

- components/MetaHead/MetaHead.tsx
- pages/share/post/[ldm].tsx
> feat: dynamic meta tag test

- hooks/useCookie.ts
- pages/_app.tsx
- pages/login/index.tsx
- pages/oauth/callback/kakao/index.tsx
- service/apis/authService.ts
> refactor: 로그인한 사용자가 로그인 페이지 진입시 홈으로 리다이렉트

- hooks/apis/member/useMemberQuery.ts
- pages/share/index.tsx
- pages/share/post/index.tsx
> 공유 페이지 ssr로 변경

- components/Home/Banner/Banner.tsx
메인홈에서 write페이지로 이동했을때 prefetch 효과가 있는지 테스트 중입니다.
Fixes (issue #268)
- Change 1
- Change 2
> refactor: next/router => next/link 로 리팩토링

- hooks/useAnimation.ts
- hooks/useBlockModal.ts
- hooks/useBottomSheet.ts
- hooks/useDialog.ts
https://www.notion.so/depromeet/001579bd7fbe4213915c2fdc49b5508d
Fixes (issue #271)
- Change 1
- Change 2
> fix: 바텀시트 close 후 overflow: hidden 유지되는 에러 수정 및 useBlockScroll hook 생성

- components/Common/DropdownMenu/DropdownMenu.tsx
- components/Common/WritingButton/WritingButton.stories.tsx
- components/Common/WritingButton/WritingButton.tsx
- components/Home/CategoryFolderList/CategoryFolderList.tsx
- components/Home/CollectedFolder/CollectedFolder.tsx
- components/Home/FloatingButton/FloatingButton.tsx
- components/Home/FloatingButtonGroup/FloatingButtonGroup.tsx
- components/Home/Folder/Folder.tsx
- components/Home/FolderList/FolderList.tsx
- components/Home/Header/Header.tsx
- components/Post/FloatingButton.tsx
- components/Post/PostList/PostList.tsx
- components/Post/WritingButton.tsx
Fixes (issue #268)
- router.push 부분을 next/link 로 변경하여 prefetch 를 통해 미리 페이지를 가져올 수 있게 변경하였습니다.
- next/link 로 변경하기 애매한 부분들은 router.prefetch 를 이용하였습니다.
> refactor: replace router.push with Link or router.prefetch

- components/Post/FloatingButton.tsx
- components/Write/AppBar.tsx
- components/Write/Layout.tsx
- pages/_app.tsx
- pages/write/index.tsx
@sujin-park  [fix: 스타일 깨진부분 수정](https://github.com/depromeet/moodpic-web/commit/87afc0fdcb943865c4e3f643b693fbc534bd24c1) 제가 구두로 말씀드린 스타일 깨진 부분 수정했습니다! 확인부탁드립니다~
- Change 1
- Change 2
> refactor&fix: 동적 Layout 추가 및 posts 페이지 style fix

- components/Home/Header/Header.tsx
> style: Link 태그로 변경하면서 발생한 스타일오류 수정

- components/Home/Banner/Banner.tsx
- components/Home/Header/Header.styles.ts
- components/Home/Header/Header.tsx
- components/Home/HomeScreenButtonSheet/HomeScreenButtonSheet.tsx
- components/Home/HomeScreenGuide/HomeScreenGuide.tsx
- components/Home/TabHeader/TabHeader.tsx
- components/Home/Tabs/Tabs.tsx
- hooks/useRandomBanner.ts
- pages/index.tsx
- shared/constants/home.ts
Reverts depromeet/moodpic-web#282
> Revert "style: 메인페이지 편집 부분 스타일 수정"
