components/Common/AppLayout/AppLayout.styles.ts
components/Common/AppLayout/AppLayout.tsx
components/Common/Header/Header.styles.ts
components/Example/Example.styles.ts
components/Example/Example.tsx
package-lock.json
pages/_app.tsx

앱 레이아웃을 간단하게 잡았습니다. (한게 없음)
생각보다 375px에 양쪽 패딩 18px이 들어가니까 컨텐츠가 많이 작아보입니다. 
캐치테이블처럼 100%이미지는 비율대로 줄도록 하고 카드형식은 가로 스크롤로 넘기지않으면 작게 보이긴 할 것 같네요..
width는 반응형으로 할지 적응형으로 할지 등 아직 정하지 않았고 서로 width를 잡는방법이 달라서 일단 뒀습니다. 화요일날에 이야기 해보는걸로 진행해보고싶습니다~ 
- Change 1
- Change 2

feat: 앱 레이아웃(컨테이너) 잡기

---

pages/mypage/withdraw.tsx
pages/posts/[postId].tsx
pages/posts/letters/[letterId].tsx
pages/posts/letters/write.tsx
pages/search/index.tsx
pages/write/complete.tsx
pages/write/current-emotion.tsx
pages/write/pre-emotion.tsx
pages/write/question.tsx

#26 
```
├─ pages
│   ├─ mypage [마이 페이지]
│   │   ├─ withdraw [탈퇴 페이지]
│   ├─ posts [글 리스트 페이지]
│   │   ├─ [postId] [글 상세 페이지]
│   │   └─ letters [편지]
│   │       ├─  [letterId] [편지 상세 페이지]
│   │       └─ write [편지 등록 페이지] 
│   ├─ search [검색 페이지]
│   ├─ write [글 작성]
│   │   ├─ pre-emotion [1차 감정 페이지]
│   │   ├─ question [글 작성 페이지]
│   │   ├─ current-emotion [2차 감정 & 폴더 & 공개설정]
│   │   └─ complete [글 작성 완료 페이지]
│   └─ index [메인 페이지]
```
구두로 논의했던 기본 Routing 에 대해서 추가하였습니다.
**추가로 편지 등록 페이지 /posts/{postId}/letters/write 를 추가하였습니다.
-> /posts/{postId}/letters 는 편지 리스트 페이지 (MVP 이후 기능) 가 추가될 수 있을 것 같아서 분리했어요!**
추가 의견 있으시면 코멘트 주세용!

Pages 기본 구조 추가

---

.storybook/main.js
.storybook/preview.js
assets/icons/close.svg
components/Common/Button/Button.stories.tsx
components/Common/Button/Button.styles.ts
components/Common/Button/Button.tsx
components/Common/ChipButton/ChipButton.stories.tsx
components/Common/ChipButton/ChipButton.styles.ts
components/Common/ChipButton/ChipButton.tsx
package-lock.json
package.json

#36
**Button** 
**Chip component**
- storybook 에서 절대경로 사용을 위해 storybook webpack 설정 변경
- storybook 에서 next/image 로드할 수 있게 설정 추가
- Button 컴포넌트 추가 (stories 추가)
- Chip 컴포넌트 추가 (stories 추가)
- close svg icon stroke 컬러 수정

공용 컴포넌트 - Button 추가

---

components/Common/Header/Header.stories.tsx
components/Common/Header/Header.styles.ts
components/Common/Header/Header.tsx
components/Home/Tabs.tsx

Fixes (issue #21)
메인페이지 Header 컴포넌트 스타일 작성
- Header 컴포넌트에 현재 디자인가이드 스타일 적용
- 메인페이지랑 다른 페이지의 Header 컴포넌트 스타일이 달라야해서 우선 MainHeader 로 함수를 분리해뒀습니다.
**최상단 페이지**
**스크롤 시**
-> 디자인 가이드랑 background color 가 조금 다른데 scroll 시에는 다른 컬러로 되어있어야해서,, 이 부분은 이후에 작업하려고 합니다!

main header 컴포넌트 추가 (#21)

---

components/Common/AppLayout/AppLayout.tsx
components/Common/Button/Button.tsx
components/Common/DropdownMenu/DropdownMenu.tsx
components/Common/Header/Header.tsx
pages/_document.tsx
pages/index.tsx
store/dropdown/atom.ts
styles/theme.ts

issue #25 
메인페이지에서 노출되는 드롭다운 메뉴
https://user-images.githubusercontent.com/29244798/166090007-9858c17d-3d7b-499d-9eaf-6c980dadc2ff.mov
**💅 style 변경**
- styles/theme font-weight normal 부분 500 으로 변경
**👏 메인페이지 드롭다운**
- DropdownMenu 컴포넌트 추가
- portal 이용해서 app 외부에서 렌더링 될 수 있게 작업하였습니다.
- dropdownStateAtom 상태 추가
-> 애니메이션은 아직 추가하지않았습니다! 아무래도 API 연동 작업을 먼저 해보는게 백엔드 파트에 좋을 것 같아서 현재 최소 기능 구현을 하고 있습니다. API 붙여보고 디테일한 디자인 & 애니메이션은 수정하겠습니다!!

메인페이지 드롭다운 메뉴 컴포넌트 추가 (#25)

---

components/Common/Header/Header.styles.ts
components/Home/Folder/Folder.styles.ts
components/Home/Folder/Folder.tsx
components/Home/FolderList/FolderList.tsx
pages/index.tsx
pages/posts/index.tsx

**issue #23**
편집 시, 편집이 가능하게 편집 버튼, 삭제 버튼이 노출되게끔 작업하였습니다.
- Header z-index 조정
- 최상단 컴포넌트에서 FolderList, Folder 컴포넌트까지 isEditMode props drilling
- Floating Action Button 추가
- msw start 하는 부분 제거
**편집 시**
**FAB 버튼**

메인페이지 > 편집 시 UI 작업 (#23)

---

components/Common/AppLayout/AppLayout.tsx
components/Common/index.tsx
components/Example/BottomSheetExample.tsx
components/Example/ModalExample.tsx
components/Home/Banner/Banner.tsx
pages/_app.tsx
pages/index.tsx

현재 아래와 같이 Common/컴포넌트이름/컴포넌트이름 으로 auto import 가 되고, export default 이기 때문에 네이밍을 다르게 하면 이후 리팩토링이 어려울 수 있다고 생각되었습니다. 
```javascript
import BottomSheetContainer from '@/components/Common/BottomSheetContainer/BottomSheetContainer';
```
named export 로 re-export 하고, 아래와 같이 Common 컴포넌트를 한번에 import 할 수 있게 변경하였습니다.
```javascript
import { CommonHeader, CommonToast } from '@/components/Common';
```

Common component re-export 리팩토링 

---

components/Common/ChipButton/ChipButton.stories.tsx
components/Common/ChipButton/ChipButton.tsx
components/Common/TagButton/TagButton.stories.tsx
components/Common/TagButton/TagButton.styles.ts
components/Common/TagButton/TagButton.tsx
components/Common/index.tsx
components/Post/PostItem.tsx/PostItem.stories.tsx
components/Post/PostItem.tsx/PostItem.tsx
pages/posts/index.tsx
public/svgs/arrowright.svg
shared/type/post.ts
styles/mixins.ts

Fixes (issue #62)
**디자인 시스템**
- 기존 ChipButton -> TagButton 로 컴포넌트 네이밍 정정했습니다.
- ChipButton 컴포넌트, stories 추가하였습니다.
**페이지 내 컴포넌트**
- PostItem 컴포넌트 추가
- /search 와 /posts 에서 사용할 수 있게 supportsTag, canEdit props 를 추가하였습니다.
- PostItem stories 추가
- /posts 페이지 기본 구성
**버그 수정**
- ellipsis mixins 내 Expression interpolation 을 잘못 작성해서 수정했습니다.
**감정 관련 Chip Button**
**태그 있는 PostItem - 검색 페이지에서 사용**
**태그 없는 PostItem - 폴더 내 리스트 페이지에서 사용**
**폴더 내 리스트 기본 구성 - 예제**
한 컴포넌트를 구성하려고 조금씩 추가하다보니 PR 이 조금 커진 것 같네요..!ㅠㅠ..

폴더 내 리스트 구성하는 아이템 컴포넌트 추가 (#62)

---

components/Common/Checkbox/Checkbox.tsx
components/Dialog/DialogFolderForm.tsx
components/Home/CollectedFolder/CollectedFolder.styles.ts
components/Home/CollectedFolder/CollectedFolder.tsx
components/Home/Folder/Folder.styles.ts
components/Home/Folder/Folder.tsx
components/Home/FolderList/FolderList.tsx
components/Post/PostItem/PostItem.tsx
components/Post/PostList/PostList.tsx
pages/index.tsx
pages/posts/index.tsx
public/svgs/right-small.svg

Feature (issue #63)
폴더 내 리스트 페이지 추가 기능 작업
1. 폴더 삭제
2. 폴더명 변경
3. 기록 여러개 선택 (편집 모드)
4. 메인페이지 폴더 컴포넌트 선택 가능하게끔 변경
**메인 페이지**
- Home/Folder, CollectedFolder 컴포넌트 cursor:pointer 스타일 적용, onClick props 전달하였습니다.
**폴더 내 리스트 페이지**
- PostList 컴포넌트 페이지 분리해서 PostList 페이지에서 `checkedItems` 핸들링할 수 있게 작업하였습니다.
- BottomSheet 에서 폴더 삭제, 폴더명 변경 다이얼로그 연결 작업하였습니다.
**Dialog**
- DialogFolderForm 컴포넌트에 `isEditMode` props 추가하여 다이얼로그 타이틀 동적으로 변경할 수 있게 하였습니다.
**여러개 기록 삭제를 위한 체크박스 선택**
https://user-images.githubusercontent.com/29244798/167448155-38e04c9f-9f4c-4eba-b70c-0a6522d6c5ca.mov
**폴더명 변경**
**폴더 삭제**
---
다음 작업 is .. 
- intersection observer
- 동일한 PostList 페이지에 folderId로 조회했을 때, categoryId로 조회했을 때에 대해 대응하는 작업을 해야겠습니다..!

폴더 내 리스트 페이지 추가 기능 작업 (#63)

---

components/Card/Card.tsx
components/Common/BottomSheetContainer/BottomSheetContainer.tsx
components/Example/BottomSheetExample.tsx
components/Post/PostDetail.style.ts
hooks/useAnimation.ts
hooks/useBottomSheet.ts
pages/posts/[postId].tsx
pages/posts/index.tsx

Fixes (issue #102)
상세페이지 bottom sheet 연결
- Card background image height 수정
- bottom sheet animation 수정
- bottom sheet 내부에 있는 버튼을 클릭 했을 때, bottom sheet 닫히고 body overflow hidden -> unset 으로 변경되지 않아서 closeModal 함수를 호출하게끔 하였습니다.
- 상세 페이지 헤더 버튼 클릭 시, bottom sheet 열리게끔 수정

상세페이지 bottom sheet 연결, bottom sheet animation 수정 (#102)

---

.prettierrc
components/Card/Card.tsx
components/Common/TextField/TextField.styles.ts
components/Common/TextField/TextField.tsx
components/Common/Toast/Toast.styles.ts
components/Example/ToastExample.tsx
components/Home/CollectedFolder/CollectedFolder.styles.ts
components/Home/FloatingButton/FloatingButton.tsx
components/Home/Folder/Folder.styles.ts
components/Home/Folder/Folder.tsx
hooks/useInput.ts
hooks/useToast.ts
pages/index.tsx

Feature (issue #64)
- prettier printWidth 80 -> 120 으로 변경하였습니다. (슬랙에서 구두 논의 완료)
- prettier printWidth 가 변경되면서 관련 변경사항들이 많이 있습니다..! 사실 해당 api 에는 그렇게 많지 않은데..
- 2차 감정 작성하지 않은 글 목록 API 연동 작업
- 메인페이지 floating button 노출 분기 처리
- 폴더 리스트 페이지 이동 시, 빈배열이어서 기록이 없어요. 노출되는 부분 확인
기존에 floating button 이 기본적으로 노출이 되고 있었는데 api 연동하면서 데이터가 없어서 아래와 같이 Floating button 이 노출되지 않는 것을 볼 수 있습니다.
페이지 이동 시, 기록이 없어요 노출

2차 감정 미선택 기록 페이지 작업 (#64)

---

pages/oauth/index.tsx
shared/constants/auth.ts
shared/constants/routes.ts

Vercel 로 배포되어있는 https://11th-5team-fe.vercel.app/ 에서 kakao login 시,
kakao redirect url 이 기본으로 http://localhost:3000 으로 되어있어서 이슈가 있습니다.
기존 KAKAO_REDIRECT_URL 에서 protocol + domain 을 제거하고, goKakaoCallback 함수 내에서 window.location.origin + kakao redirect url 을 조합하여 redirect url로 만들었습니다.

kakao redirect url location -> window.location.origin 으로 변경

---

components/Card/Card.tsx
components/Home/CategoryFolderList/CategoryFolderList.tsx
components/Home/Folder/Folder.styles.ts
components/Home/Folder/Folder.tsx
components/Home/FolderList/FolderList.tsx
components/Post/PostList/PostList.tsx
hooks/apis/folder/useFolderMutation.ts
hooks/apis/folder/useFoldersQuery.ts
hooks/apis/post/index.ts
hooks/apis/post/usePostsQuery.ts
pages/index.tsx
pages/posts/index.tsx
service/apis/postService.ts
shared/constants/category.ts
shared/type/post.ts

Fixes (issue #23)
폴더 추가, 폴더 수정, 폴더 삭제 관련 로직 추가
**메인페이지**
- 폴더 추가, 폴더 수정, 폴더 삭제 mutation 추가 mutate 함수 호출해서 onSuccess, onError 처리 작업
**폴더 리스트 페이지**
- 폴더별 (folderId), 감정별 (categoryId), 모든 글 목록 querystring 을 기준으로 fetching query, data 변경
**공통**
- 감정이라는 단어를 category, emotion 으로 다 다르게 쓰고 있었던 부분을 category 로 통일
- invalidateQueries -> resetQueries 로 변경

메인페이지 폴더 추가, 수정, 삭제 관련 로직 추가 (#23)

---

components/Common/TextField/TextField.styles.ts
components/Post/FloatingButton.tsx
components/Post/PostDetail.style.ts
components/Post/PostItem/PostItem.stories.tsx
pages/posts/[postId].tsx
pages/posts/[postId]/edit.tsx
pages/posts/index.tsx
public/svgs/arrow-right-primary.svg
service/apis/postService.ts
shared/type/post.ts

Fixes (issue #35)
수정 페이지, 상세 페이지 디테일 작업
- Textfield right side icon position 변경
- cc. @guymoon 혹시 이후 기문님 작업에 영향이 있을지 확인해주시면 좋을 것 같습니다!
- getPosts service 함수 return value 변경
- 이전에 { posts, totalCount } 로 반환되지 않아서 프론트에서 처리해줬었는데 API Response 가 변경되어 수정하였습니다.
- 기록 완료 -> 상세페이지에서만 사용되는 Floating button 추가
- Post interface 에 my property 추가, PostListResponse 에 categoryName property 추가
- 수정페이지에서 router.isReady true 일 때 fetchPostById 실행할 수 있게 작업
**AS-IS Textfield width 100% 되지 않는 이슈**
**TO-BE Textfield width 100%**
**태그 스타일 버그 수정**
**작업 완료 페이지에서만 보이는 Floating Button 추가**
- API 개발되면 수정 페이지에서 기존 folderId 를 가져오는 작업 진행 예정입니다.

기록 상세 페이지, 수정 페이지 디테일 작업 (#35)

---

components/BottomSheetCategoryList/BottomSheetCategoryList.tsx
components/Common/AppLayout/AppLayout.styles.ts
components/Common/BottomSheetContainer/BottomSheetContainer.tsx
components/Post/PostItem/PostItem.stories.tsx
components/Post/PostItem/PostItem.tsx
components/Post/PostList/PostList.tsx
hooks/post/usePostEditForm.ts
pages/posts/[postId]/edit.tsx
pages/posts/index.tsx
shared/type/post.ts

Fixes (issue #35)
- BottomSheetCategoryList 컴포넌트 추가
- 감정 리스트 바텀시트로 사용하기 위해 추가하였습니다.
- BottomSheetWrap 에 있는 이벤트 핸들러 제거
- usePostEditForm custom hooks 추가
- firstCategoryName, secondCategoryName property 추가 (API 에서 추가해준 필드 추가하였습니다!)
**💅 style**
- AppLayout container background color 변경 (gray6 -> #000)
**모르겠어요 선택한 글 수정 시, 하단 바텀시트 노출**
**480px 초과하는 width background #000 으로 변경**

감정 리스트 bottom sheet 추가

---

hooks/useIsMounted.ts
pages/index.tsx

Fixes (issue #25 )
[레퍼런스](https://usehooks-ts.com/react-hook/use-is-mounted)를 참고하여 useIsMounted hooks 를 만들었는데,
client side 에서 isMounted() 가 false 로 되어 메인 배너가 노출되지 않는 이슈가 있었습니다.
그래서 useIsMounted hooks 를 수정하였고, isMounted 가 바뀔 때마다 setIsMounted 에 elementRef.current 값을 바인딩하는 방향으로 버그를 해결하였습니다.

useIsMounted hooks 로직 변경 

---

components/Common/ButtonWithIcon/ButtonWithIcon.stories.tsx
components/Common/ButtonWithIcon/ButtonWithIcon.tsx
components/Common/index.tsx
components/Post/FloatingButton.tsx

Fixes (issue #132)
- ButtonWithIcon 컴포넌트 추가
- 현재는 icon 을 고정으로 두었습니다. 이후에 확장이 필요하면 icon 을 props 로 받을 수 있게 변경하겠습니다!
- post 상세 페이지 내 ButtonWithIcon 적용 
**아이콘 + 버튼**
**상세 페이지 적용 (with gradation)**

공유하기, 상세 페이지에서만 사용되는 버튼 컴포넌트 재사용 할 수 있게 추가 (#132)

---

components/Home/CollectedFolder/CollectedFolder.styles.ts
components/Home/CollectedFolder/CollectedFolder.tsx
components/Home/FolderList/FolderList.tsx
components/Post/PostDetail.style.ts
components/Post/PostItem/PostItem.tsx
hooks/useRandomBanner.ts
pages/index.tsx

Fixes (issue #25)
- 메인페이지 **모든 폴더** 영역을 api 에서 전달해주는 postsThumbnail 을 이용하여 작업하는 것으로 변경하였습니다.
- 기존에는 thumbnail max size 4 와 모든 폴더 배열 length 를 비교하고 slice 하는 작업을 하였는데 제거하였습니다.
- 다만 아래와 같이 유효한 썸네일인지를 체크하는 작업을 하였습니다. 현재 API 에서 글이 없을 때 default 이미지를 전달해주고 있는데 default 이미지는 프론트에서 노출하면 안되기 때문에 아래와 같이 한번 더 체크하는 작업을 했습니다..!
(이후 백엔드 협의 요청할 예정이고, 아래 코드는 지워질 것 같습니다.)
```jsx
const validThumbnails = items.map((item, index) => (index < count ? item : ''));
```
- randomTitle, randomImageSource hooks 내에서 useEffect hooks 를 이용하여 최초 한번만 실행되게 변경하였습니다.
- 다른 모달, 버튼 클릭 시 Banner 컴포넌트가 리렌더링 되면서 계속 random 으로 변경되는 버그가 있었습니다.
- Banner 컴포넌트에 전달되는 props 가 아닌 다른 값들이 변경될 때 Banner 가 리렌더링 되지 않게 최적화 하는 작업도 필요하지만 우선 버그 수정을 위해 위와 같은 작업을 진행하였습니다.
- PostItem 컴포넌트 내에서 태그 갯수 너비에 맞춰서 보여줄 수 있는 태그만 보여줄 수 있게 overflow: hidden 으로 숨김 처리 …

CollectedFolder 스타일 수정, Random Banner 컴포넌트 hooks 수정 (#25)

---

hooks/apis/folder/useFoldersQuery.ts
hooks/apis/post/usePostsQuery.ts
hooks/useIntersectionObserver.ts
pages/posts/[postId].tsx
pages/posts/index.tsx
service/apis/postService.ts
shared/type/common.ts
shared/type/post.ts

Fixes (issue #62, #63)
- useIntersectionObserver hooks 추가
**사용방법**
```jsx
const { setEntry } = useIntersectionObserver({
onIntersect: ([{ isIntersecting }]) => {
if (isIntersecting && hasNextPage) {
fetchNextPage();
}
},
}); 
return (
<>
<div ref={setEntry}>Loading</div>
</>
)
```
- post 리스트 페이지 내 무한 스크롤 적용
- post list api 모두 useInfiniteQuery 로 변경
- return value 에 hasNext totalCount, page, size 로 계산하여 추가
- size 는 고정값 (PAGE_SIZE) 으로 사용하고 있다보니 parameter 에서 모두 제거하고 page 만 받게 변경하였습니다.
https://user-images.githubusercontent.com/29244798/171973016-1219c805-04f9-4852-ba75-042f1561502b.mov
- pre-rendering 시 router.query object 가 비어있어서 useQuery 실행 시 enabled 옵션을 사용하였습니다. (이전 쿼리에 의존할 때 사용하여야 하는데 잘못 사용하고 있는 부분이라서 이후 리팩토링 할 예정입니다.)
- React Query 사용하는 부분 모두 리팩토링 예정입니다. (useQueryClient hooks 를 사용해야 하는 …

기록 리스트 페이지 무한스크롤

---

components/Common/AppLayout/AppLayout.tsx
components/Home/CollectedFolder/CollectedFolder.styles.ts
components/Home/CollectedFolder/CollectedFolder.tsx
components/Home/Folder/Folder.tsx
components/Post/PostItem/PostItem.tsx
hooks/apis/post/useFirstCategoryQuery.ts
pages/posts/[postId].tsx
shared/utils/formatter.ts
shared/utils/storePathValues.ts

Fixes (issue #132)
기록 작성 후, 상세페이지 내에 홈으로 돌아가기 버튼이 노출되어야 하는 이슈가 있습니다.
- storePathValues 함수 추가 (ref. https://www.grouparoo.com/blog/getting-previous-path-nextjs)
- sessionStorage 에 prevPath, currentPath 를 저장하여 previous path 를 유지하는 작업을 추가하였습니다.
- AppLayout 에서 storePathValues 실행
- 현재는 /write -> post detail 페이지로 이동할 때만 previous path 를 알면 되지만, 전체적인 구조를 봤을 때 특정 페이지가 아닌 AppLayout 에서 실행하는게 맞는 것 같아서 AppLayout 에 추가하였습니다!
- `commaNumber` 함수 추가
- 조회수, 폴더 글 갯수와 같이 숫자 포맷팅을 하기 위해 추가하였습니다.
- 메인 페이지 모든 폴더 컴포넌트 버그 수정
- api response 가 변경되면서 맞춰주기 위해 로직을 변경하였습니다.

previous path 가 기록 작성 페이지일 때, 상세 페이지 버튼 노출 (#132)

---

components/BottomSheetCategoryList/BottomSheetCategoryList.tsx
components/CategorySelector/CategorySelector.stories.tsx
components/CategorySelector/CategorySelector.tsx
components/CurrentEmotion/CurrentEmotion.tsx
components/Post/PostEdit.style.ts
pages/posts/[postId]/edit.tsx
pages/posts/dontknow-feelings.tsx

Fixes (issue #35)
- CategorySelector 컴포넌트 select -> button 으로 변경
- select 에서 button 으로 변경하면서 category list 데이터 구조를 변경하지 않아도 되서 options interface 를 변경하였습니다.
- 모르겠어요 선택한 기록 리스트 페이지 API 연결 작업
**CategorySelector 컴포넌트 내 arrow-icon 제거**
**CategorySelector 클릭 시, 하단 바텀시트 노출**

수정 페이지 내 감정 선택하는 컴포넌트 수정 (#35)

---

components/Common/TextArea/TextArea.styles.ts
components/Dialog/DialogFolderForm.tsx
components/Home/CollectedFolder/CollectedFolder.tsx
components/Home/Folder/Folder.tsx
components/Home/FolderList/FolderList.tsx
hooks/apis/post/usePostsQuery.ts
pages/index.tsx
pages/posts/[postId].tsx
pages/posts/index.tsx

https://www.notion.so/depromeet/QA-27c48bd47fd94b6f94e17b464532caeb
노션에 있는 QA 이슈 해결
**style**
- Textarea component background 수정
**fix**
- 모든 폴더 -> 모든 기록으로 키워드 변경
- 상세 페이지에서 Textarea 에 focus 할 수 없게 변경 (readonly -> disabled 로 변경)
- 폴더 편집 시, 폴더 변경 팝업에 기본 폴더명 노출되게 수정
- 폴더 변경/추가 팝업 닫을 때, inputValue 초기화 작업
- 폴더 리스트에서 폴더 변경 시, refetch 실행
**기능 개선**
- 폴더 추가/변경 팝업 노출 시, autoFocus 되게 attribute 추가

메인페이지, 리스트 페이지, 상세 페이지 관련 QA 이슈 해결

---

shared/utils/copyClipboard.ts

사파리에서 클립보드 복사가 되지 않아 방식을 수정했습니다. deprecated 된 방식이지만 QA를 위해 우선 수정하고 추후에 다른 방법을 찾아 적용 할 수 있도록 하겠습니다.
Fixes (issue #161 )
- navigator.clipboard 대신 document. execCommand 방식으로 수정 

fix: safari에서 navigator.clipboard 지원하지 않아 클립보드 카피 방법 수정

---

components/Common/TextArea/TextArea.styles.ts
pages/posts/[postId].tsx
pages/posts/[postId]/edit.tsx

메인페이지, 수정페이지 노션 QA 해결
- 수정 페이지에서 문답형인지 체크하지않고 무조건 content 구분자로 문자열을 합치다보니 자유형도 수정하고나면 문답형으로 바뀌는 버그가 있었습니다.
- 문답형인지 체크하고 문답형일 때만 join 할 수 있게 변경하였습니다.
- webkit browser 에서 textarea disabled 일 때 색상을 변경하기 위해 속성을 추가하였습니다.
- webkit-text-fill-color 를 추가하고, opacity: 1 을 주었습니다.

메인페이지, 수정페이지 QA 이슈 해결

---

components/Home/CollectedFolder/CollectedFolder.styles.ts
components/Home/FloatingButton/FloatingButton.tsx
pages/posts/[postId]/edit.tsx
pages/posts/index.tsx

Fixes (issue QA 이슈)
- 모든기록 background color 변경하였습니다.
- 모르겠어요 FAB 버튼 box-shadow 를 추가하였습니다.
- 리스트 페이지 편집 시, AppBar 에 닫기 버튼만 노출될 수 있게 변경하였습니다.
- 수정 페이지에서 뒤로가기 시, toggleDialog 함수 실행 및 dialogType 도 변경하였습니다.
**모든기록, 미분류 폴더 사이즈 동일하게 변경**
**모르겠어요 버튼 box-shadow 추가**

메인페이지 스타일 수정, 폴더 리스트 페이지 앱바 수정 

---

components/Home/CollectedFolder/CollectedFolder.tsx
components/Home/Folder/Folder.tsx
components/Home/FolderList/FolderList.tsx
components/Post/PostItem/PostItem.tsx
components/Post/PostList/PostList.style.ts
pages/posts/[postId].tsx
pages/posts/[postId]/edit.tsx

Fixes (issue 리스트 페이지 QA)
- 수정페이지, 상세페이지에서 Nickname 노출되게끔 수정하였습니다.
- 내 글일 때는 nickname 노출하고 아닐 때는 **유저** 라고 해두었습니다. 해당 부분은 기획 확인해서 다시 수정 예정입니다.
- 수정, 상세페이지에서 질문 번호를 제거하였습니다.
- Folder 컴포넌트 미분류, 모든폴더 상관없이 편집 모드일 때는 클릭되지 않게 수정하였습니다.

리스트 페이지 QA 이슈 해결

---

shared/utils/date.ts

Safari 에서 2022-01-01 13:00:00Z 에 대한 string 을 date 로 생성할 때, Invalid Date 로 처리되어
에러가 발생하고 있습니다. (사실 이 부분에서 제가 좀 더 확실한 방법으로 했어야 했는데, 단순히 Z 를 붙여서 작업하는 방식으로 해서 그런 것 같습니다ㅠㅠ)
1. 2022-01-01 13:00:00 부분을 year, month, date, hour, min 으로 split 을 하고
2. Date.UTC(year, month, date, hour, min) 으로 UTC 밀리초로 변환
3. new Date() 생성자로 호출하여 로컬 타임존에 맞춰 date 객체를 반환하여
4. Intl.DateTimeFormat 을 이용하여 yyyy년 mm월 dd일 hh:mm 로 노출될 수 있게 작업하였습니다.

date format 함수 Safari 버그 수정

---

components/Share/CategoryOptionItem/CategoryOptionItem.tsx
pages/share/index.tsx
shared/utils/copyClipboard.ts
styles/theme.ts

검색 기능 이슈 처리 
- 공유하기 기능에서 감정 기본 선택 값 선택안함 으로 변경 (기존에는 null)
- 공유하기 감정 선택 시 border 스타일 추가 
- 공유하기 취소 시 경고 메시지 수정 

공유 기능 기본 선택 값 및 메시지 수정

---

components/Common/TextField/TextField.stories.tsx
components/Common/TextField/TextField.styles.ts
components/Common/TextField/TextField.tsx
components/Common/Toggle/Toggle.styles.ts
components/Common/index.tsx
components/CurrentEmotion/CurrentEmotion.tsx
components/Dialog/DialogDelete.tsx
components/Dialog/DialogFolderForm.tsx
components/Post/PostDetail.style.ts
components/Post/PostEdit/Question.tsx
hooks/apis/folder/useFolderMutation.ts
pages/posts/[postId].tsx
pages/posts/[postId]/edit.tsx
service/apis/folderService.ts
shared/type/folder.ts

https://www.notion.so/depromeet/QA-27c48bd47fd94b6f94e17b464532caeb
QA 이슈 수정
- TextField 컴포넌트에 있는 hasBorder 를 제거하고, focus style 로 변경하였습니다. 
- focus 됐을 때 border 가 변경되어야 한다면 hasBorder 와 같은 props 없이 focus 스타일로만 할 수 있어서 수정했습니다.
- Toggle button style 수정하였습니다.
- 수정 페이지에서 createFolderMutation onSuccess 에서 추가된 folderId 를 할당하였습니다.

Fix: Textfield, 수정 페이지 QA 이슈 수정

---

components/Post/PostItem/PostItem.tsx
pages/search/result/index.tsx

Fixes (issue #192)
- PostItem 컴포넌트 마크업 구조 수정하였습니다.
- supportsTag -> isSearchedByTag 로 props naming 수정하였습니다.
- 검색 페이지에서 tag on/off 만 하고자 supportsTag 로 작성했었는데, 검색 페이지에서 분기처리가 많이 되어 isSearchedByTag 로 하였습니다.
**검색 페이지**
**검색 페이지 - 내 글**
**내 글 리스트**

style: PostItem 컴포넌트 스타일 수정 (#192)

---

components/Card/Card.styles.ts
components/CategorySelector/CategorySelector.tsx

감정 그래픽 이미지를 가지고 있는 컴포넌트 스타일 수정이 필요하였습니다.
- CategorySelector 컴포넌트 내 Category image width, height 를 변경하고, position bottom 을 변경합니다.

style: 감정그래픽 Card, Category Selector 컴포넌트 스타일 수정 

---

pages/posts/dontknow-feelings.tsx

https://www.moodpic.kr/posts/posts/4fbf8916-511d-4073-9e84-72c75617762a
위와 같이 /posts/posts/${postId} 로 이동되며 없는 페이지라서 404가 노출됩니다.
/posts/dontknow-feelings 페이지에서 PostItem 클릭 시, router.push 함수를 실행할 때 상대경로로 잘못 작성하여
`/posts/posts/${postId}` 로 이동하면서 404 에러가 발생하였습니다.
router.push 할 때 `/posts/${post.id}` 로 이동할 수 있게 변경하였습니다.

Fix: 모르겠어요 페이지에서 상세 페이지로 이동시 404 에러 

---

shared/utils/fetcher.ts

Fixes (issue #234)
authToken 은 있는데 해당 토큰이 만료되어 api 호출 시 401에러만 발생하고 로그인 페이지로 이동하지 않는 이슈
authToken 이 없을 때는 middleware 에서 처리가 되지만, authToken 이 있으면 인증된 회원으로 간주하여 메인페이지 접근이 가능합니다.
-> axios response interceptor 에서 error.response.status 가 401 인 경우 token 을 제거하고, 새로고침을 하여 로그인으로 이동하게끔 하였습니다.
moodpic 에 오랜만에 들어가니 토큰이 만료되어 위와 같은 이슈를 맞이하여 수정해보았습니다.

Fix: auth token 만료되었을 때, 로그인으로 가지 않고 API 401 에러만 나는 이슈 수정 

---

components/Common/TextArea/TextArea.styles.ts
components/Common/TextArea/TextArea.tsx

Textarea height 가 고정되어있고 텍스트를 고정된 height 보다 많이 작성하는 경우 하단 padding 을 벗어나 텍스트가 노출되는 이슈가 있습니다.
- textarea 를 감싸는 container div element 를 추가하고, 해당 element 에 padding 을 추가하였습니다.
- textarea 감싸는 div 에 isFocused 를 props 로 전달하여 포커스 될 때 border style 을 적용하였습니다.
**AS-IS**
**TO-BE**

fix: Textarea 컴포넌트 padding 유지를 위해 wrapper 추가

---

pages/_app.tsx
pages/_document.tsx

next/script는 HTML <script> 요소의 확장으로 추가 스크립트를 가져오고 실행할 때 최적화된다고 하여 리팩토링을 하였습니다.
아래 링크를 참고하여 수정해보았습니다!
ref. https://github.com/vercel/next.js/blob/canary/examples/with-google-tag-manager/pages/_app.js

refactor: next/script 사용하는 방식으로 변경
